# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project, GKE_EMAIL with the service account email, GKE_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER, IMAGE, REGISTRY_HOSTNAME and DEPLOYMENT_NAME environment variables (below).

name: Build and Deploy to GKE

on:
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-west1-a
  GKE_CLUSTER: example-gke-cluster
  IMAGE: gke-test
  REGISTRY_HOSTNAME: gcr.io
  DEPLOYMENT_NAME: gke-test

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build
      run: |        
        docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:$GITHUB_SHA
        
    # Set up kustomize
    - name: Set up Kustomize
      run: |
        curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
        ./kustomize edit set image $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${GITHUB_SHA}
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
        !DOCTYPE HTML>
<html>
<head>
	<title>Mbakwe Abundant Portfolio Website</title>
	<link rel="stylesheet" type="text/css" href="portfolio.css"></link>
</head>
<body>
	
	<section class="container">
	<div class="half-width">
	<h1> <span style='color: white;'> Welcome to </span> <span class='maths'>Mbakwe Abundant</span><span style="color: white;"> Portfolio</span> </h1>
	<h3>The wonderful footballer and aspiring Web Developer</h3>
	<p>As you all know ,my name is Abundant Chibuike Mbakwe.I was born and brought up in Lagos state but my state of origin is the wonderful Anambra state.What i like to do during my leisure time is playing football.But nobody pays me a dime for playing football,it's just a passion or you can say hobby.That is why i'm learning and mastering web development and also some technical skills like application development,Graphic designing and so on.I will not stop until i become a Web Development Hero.</p>
  </div>
<div class="half-width">
	<img class="side-img" src="abun.jpg" ></img>
</div>
<a class="abun" href="tel:09015688021">Hire Me</a>
</section>
<section class="container">
	<div class="half-width">
		<img class="side-img" src="pro.jpg" style="width: 300px" height="300px"></img>
	</div>
	<div class="half-width">
		<h2 style="color: #8845f4;">BIG DREAM</h2>
		<h4>Become a Web Developer</h4>
		<p>I already learned the basic HTML and CSS.I can build any simple website.I can even teach my brothers how to make a simple website with knowledge on HTML and CSS.My goal is to build 3D websites and learn advanced topics.</p>
		<a class="abun" href="#">Email:mbakweabundant@gmail.com </a>
	</div>
</section>
<section class="container experiences" class="experiences">
	<h2>EXPERIENCE</h2>
	<div class="experience-item">
		<h3>Full Stack Web Developer</h3>
		<p class="maths">2020-Present|Novice Level Developer</p>
		<p>I am a novice in HTML,CSS and JAVASCRIPT.I know a little needed to make a website function efficiently like i said earlier that i'm still a novice</p>
	</div>
</section>
<footer>
	<ul>
		<li><a href="https://www.instagram.com/mbakweabundant/"><img style="width: 50px;" style="height: 50px;" src="IG.png"></img></a></li>
		<li><a href="https://www.whatsapp.com/09015688021"><img style="width: 50px;" style="height: 50px;" src="whatsapp.jpeg"></img></a>
		</li>
		<li><a href="https://www.twitter.com/abundant_mbakwe"><img style="height: 50px;" style="width: 50px;" src="twitter.jpeg"></img></a>
		</li>
		<li><a href="mailto:mbakweabundant@gmail.com"><img style="width: 50px;" style="height: 50px;" src="email.jpeg"></img></a></li> 
	</ul>
	<p style="text-align: center;
	">Copyrights inc Mbakwe Abundant 2020 , a Novice Web Developer
<br style="color: #777777;">Click on the social media logos above to visit our respective social media profile<br></p>
</footer>
</body>
</html> 
